export const ARENA_EVENTS_NAMES = {
  ARENA_USER_EXECUTE_ACTION: "ARENA_USER_EXECUTE_ACTION",
  ARENA_TURN_STARTED: "ARENA_TURN_STARTED",
  ARENA_BATTLE_STARTED: "ARENA_BATTLE_STARTED",
  ARENA_BATTLE_ENDED: "ARENA_BATTLE_ENDED",
} as const;
